// <auto-generated />
namespace BigHero.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addnewaddressforuser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addnewaddressforuser));
        
        string IMigrationMetadata.Id
        {
            get { return "201508080414338_add new address for user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
